CombatFlite XML import & AH-64D elevation fix
the-paid-actor/dcs-dtc pull request #52
Opened 2022-11-06 09:07 UTC by PieterL1976

- implemented Combatflite XML import for Viper & Hornet
- fixed locale bug with CombatFlite XML import
- enabled empty elevation for AH-64D waypoints

2022-11-06 17:38 UTC, p-louis requested changes
Overall LGTM just a small change and please make sure the `replace(',','.')` stuff does work with other locales just as well.

2022-11-06 17:38 UTC, p-louis commented on dcs-dtc/Models/AH64/Waypoints/Waypoint.cs
> +            try
This block could be simplified to
```
int? elev = null;
int.TryParse(elevation, elev)
return new Waypoint(0, type, ident, free, mgrs, elev);
```

Also please remove the commented out lines at the end

2022-11-06 17:38 UTC, p-louis commented on dcs-dtc/Models/FA18/FA18Configuration.cs
> +                var dLat = double.Parse(lat.Replace(',', '.'));
Has this be verified with different locales? For example in german locale, the decimal point is replaced with a decimal comma.

2024-01-13 00:00 UTC, the-paid-actor commented
Check V7 published today

2024-01-13 00:00 UTC, closed without merging